# -*- coding: utf-8 -*-
"""QR_Code_Maker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUgzWXKSPQ_qobBtLyOU5eFytKuqiBhD
"""

!pip install qrcode[pil]

import qrcode

# Your Google Maps link
url = "https://goo.gl/maps/WRoCoZdn3AQ6Ads46"

# Generate QR code
qr = qrcode.QRCode(
    version=1,  # controls the size of the QR Code
    error_correction=qrcode.constants.ERROR_CORRECT_L,  # error correction
    box_size=10,  # size of the box where QR code is displayed
    border=4,  # thickness of the border
)

qr.add_data(url)
qr.make(fit=True)

# Create an image from the QR Code instance
img = qr.make_image(fill="black", back_color="white")

# Save the image as a PNG file
img.save("/content/sample_data/google_maps_qr_code.png")

print("QR code generated and saved as google_maps_qr_code.png")

